---
title: "'Catch' を 'Try' ステートメントの外に置くことはできません"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: b5097910fa669c320e2e1b57d8d090b5d66f0956
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074525"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' を 'Try' ステートメントの外に置くことはできません

`Catch` は `Try...Catch...Finally` ステートメント ブロック内に置く必要があります。 不要な `Catch` ステートメントが `Try` ブロック内にあるか、または `Catch` ステートメントが、対応する `Try` ブロックの境界の外側にあります。  
  
 **エラー ID:** BC30380  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. 不要な場合は `Catch` ステートメントを削除します。または、 `Try...Catch...Finally` ステートメント ブロック内に置きます。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
