---
title: "'Catch' を 'Try' ステートメントの外に置くことはできません"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: f9ce965d1d983743796f8cc66ae20ffb018a07bc
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/23/2019
ms.locfileid: "62027538"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' を 'Try' ステートメントの外に置くことはできません
`Catch` は `Try...Catch...Finally` ステートメント ブロック内に置く必要があります。 不要な `Catch` ステートメントが `Try` ブロック内にあるか、または `Catch` ステートメントが、対応する `Try` ブロックの境界の外側にあります。  
  
 **エラー ID:** BC30380  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. 不要な場合は `Catch` ステートメントを削除します。または、 `Try...Catch...Finally` ステートメント ブロック内に置きます。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
