---
title: "'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 13b8ce225fe487b0c597a6fe81983543e5af535e
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/23/2019
ms.locfileid: "61976028"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' を 'Try' ステートメント内にある 'Finally' の後に置くことはできません
コード内で `Catch` ステートメントが、 `Finally` ステートメント ブロックの末尾の `Try` の後にあります。 `Catch` は `Try...Catch...Finally` ステートメント ブロック内に置く必要があります。  
  
 **エラー ID:** BC30379  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
1. `Catch` ステートメントをコード内の適切な場所に移動します。  
  
## <a name="see-also"></a>関連項目

- [Try...Catch...Finally ステートメント](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
