---
title: "'Catch' ブロックに到達しませんでした。'<exception>' は、同じ Try ステートメントで処理しました。"
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 5133bfd9b4471350691407dee09feec2d3af444a
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/23/2020
ms.locfileid: "91084555"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>'Catch' ブロックに到達しませんでした。'\<exception>' は、同じ Try ステートメントで処理しました。

先行する `Catch` ブロックで処理されるため、コードの `Try` ブロックには到達できません。  
  
既定では、このメッセージは警告です。 警告を非表示にする方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」をご覧ください。
  
 **エラー ID:** BC42031  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 不要なステートメントを削除します。  
  
## <a name="see-also"></a>こちらもご覧ください

- [Try ブロックと Catch ブロックを使用して例外をキャッチする方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [ユーザー フィルター例外ハンドラーの使用](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally ステートメント](../language-reference/statements/try-catch-finally-statement.md)
