---
title: "' Catch' ブロックに到達しません。<exception>同じ 'Try' ステートメントで処理しました。"
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: e05a324e67f279c650626833a6745f28df388c0d
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/28/2019
ms.locfileid: "64627198"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>' Catch' ブロックに到達しません。\<例外 > 同じ 'Try' ステートメントで処理しました。
先行する `Catch` ブロックで処理されるため、コードの `Try` ブロックには到達できません。  
  
既定では、このメッセージは警告です。 警告を表示しない方法や、警告をエラーとして扱う方法の詳細については、「 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)」を参照してください。
  
 **エラー ID:** BC42031  
  
## <a name="to-correct-this-error"></a>このエラーを解決するには  
  
- 不要なステートメントを削除します。  
  
## <a name="see-also"></a>関連項目

- [例外をキャッチする try/catch ブロックを使用する方法](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [ユーザー フィルター例外ハンドラーの使用](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try...Catch...Finally ステートメント](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
