---
title: 例外と例外処理 - C# プログラミング ガイド
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: b883012cf8f72247ff4e0b47a46eee1854e2d534
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: HT
ms.contentlocale: ja-JP
ms.lasthandoff: 03/15/2020
ms.locfileid: "76735647"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="e43f2-102">例外と例外処理 (C# プログラミング ガイド)</span><span class="sxs-lookup"><span data-stu-id="e43f2-102">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="e43f2-103">C# 言語の例外処理機能は、プログラムの実行時に発生する予期しない状況や例外的な状況を扱うのに役立ちます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-103">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="e43f2-104">例外処理では、キーワード `try`、`catch`、および `finally` を使用して、成功しない可能性があるアクションを試行し、適切な場合はエラーを処理して、後からリソースをクリーンアップします。</span><span class="sxs-lookup"><span data-stu-id="e43f2-104">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="e43f2-105">例外の発生元は、共通言語ランタイム (CLR)、.NET Framework、または任意のサード パーティ ライブラリ、またはアプリケーション コードなどさまざまです。</span><span class="sxs-lookup"><span data-stu-id="e43f2-105">Exceptions can be generated by the common language runtime (CLR), by the .NET Framework or any third-party libraries, or by application code.</span></span> <span data-ttu-id="e43f2-106">例外は、`throw` キーワードを使用して作成されます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-106">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="e43f2-107">コードが直接呼び出したメソッドではなく、呼び出し履歴の下の方にある別のメソッドによって例外がスローされることも多くあります。</span><span class="sxs-lookup"><span data-stu-id="e43f2-107">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="e43f2-108">その場合、CLR は履歴をアンワインドし、`catch` ブロックを持つメソッドを探して特定の例外の種類がないかを調べ、もしあれば最初に見つかった `catch` ブロックを実行します。</span><span class="sxs-lookup"><span data-stu-id="e43f2-108">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="e43f2-109">適切な `catch` ブロックが呼び出し履歴にない場合は、プロセスが終了し、ユーザーにメッセージが表示されます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-109">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="e43f2-110">この例では、メソッドが 0 による除算をテストしてエラーをキャッチします。</span><span class="sxs-lookup"><span data-stu-id="e43f2-110">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="e43f2-111">例外処理せずにプログラムは終了し、"**DivideByZeroException はハンドルされませんでした。** " というエラーが表示されます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-111">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="e43f2-112">例外の概要</span><span class="sxs-lookup"><span data-stu-id="e43f2-112">Exceptions Overview</span></span>

<span data-ttu-id="e43f2-113">例外には、次の特徴があります。</span><span class="sxs-lookup"><span data-stu-id="e43f2-113">Exceptions have the following properties:</span></span>

- <span data-ttu-id="e43f2-114">例外はすべて最終的に `System.Exception` から派生した種類になります。</span><span class="sxs-lookup"><span data-stu-id="e43f2-114">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="e43f2-115">例外をスローする可能性のあるステートメントの周囲で `try` ブロックを使用します。</span><span class="sxs-lookup"><span data-stu-id="e43f2-115">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="e43f2-116">`try` ブロックで例外が発生すると、コントロールのフローが、呼び出し履歴内の関連付けられている最初の例外ハンドラーにジャンプします。</span><span class="sxs-lookup"><span data-stu-id="e43f2-116">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="e43f2-117">C# では、`catch` キーワードは例外ハンドラーの定義に使用されます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-117">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="e43f2-118">特定の例外の例外ハンドラーが存在しない場合、プログラムは実行を停止し、エラー メッセージを表示します。</span><span class="sxs-lookup"><span data-stu-id="e43f2-118">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="e43f2-119">処理できない例外はキャッチしないようにして、アプリケーションを既知の状態に保ちます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-119">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="e43f2-120">`System.Exception` をキャッチした場合は、`catch` ブロックの最後で `throw` キーワードを使用して、それを再スローします。</span><span class="sxs-lookup"><span data-stu-id="e43f2-120">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="e43f2-121">`catch` ブロックで例外変数を定義した場合、それを使用して、発生した例外の種類に関する詳細を入手することができます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-121">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="e43f2-122">例外は、`throw` キーワードを使用してプログラムで明示的に生成することができます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-122">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="e43f2-123">例外オブジェクトには、呼び出し履歴の状態やエラーの説明など、エラーに関する詳細情報が含まれています。</span><span class="sxs-lookup"><span data-stu-id="e43f2-123">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="e43f2-124">`finally` ブロック内のコードは、例外がスローされた場合でも実行されます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-124">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="e43f2-125">`finally` ブロックを使用してリソースを解放します。たとえば、`try` ブロックで開かれたストリームまたはファイルを閉じます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-125">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="e43f2-126">.NET Framework のマネージド例外は、Win32 構造化例外処理メカニズムの上に実装されます。</span><span class="sxs-lookup"><span data-stu-id="e43f2-126">Managed exceptions in the .NET Framework are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="e43f2-127">詳細については、「[構造化例外処理 (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp)」と「[A Crash Course on the Depths of Win32 Structured Exception Handling (Win32 構造化例外処理に関する短期集中コース)」](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm)を参照してください。</span><span class="sxs-lookup"><span data-stu-id="e43f2-127">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="e43f2-128">関連項目</span><span class="sxs-lookup"><span data-stu-id="e43f2-128">Related Sections</span></span>

<span data-ttu-id="e43f2-129">例外と例外処理の詳細については、次のアーティクルを参照してください。</span><span class="sxs-lookup"><span data-stu-id="e43f2-129">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="e43f2-130">例外の使用</span><span class="sxs-lookup"><span data-stu-id="e43f2-130">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="e43f2-131">例外処理</span><span class="sxs-lookup"><span data-stu-id="e43f2-131">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="e43f2-132">例外の作成とスロー</span><span class="sxs-lookup"><span data-stu-id="e43f2-132">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="e43f2-133">コンパイラにより生成された例外</span><span class="sxs-lookup"><span data-stu-id="e43f2-133">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="e43f2-134">try/catch を使用して例外を処理する方法 (C# プログラミング ガイド)</span><span class="sxs-lookup"><span data-stu-id="e43f2-134">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="e43f2-135">finally を使用してクリーンアップ コードを実行する方法</span><span class="sxs-lookup"><span data-stu-id="e43f2-135">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="e43f2-136">CLS に準拠していない例外をキャッチする方法</span><span class="sxs-lookup"><span data-stu-id="e43f2-136">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="e43f2-137">C# 言語仕様</span><span class="sxs-lookup"><span data-stu-id="e43f2-137">C# Language Specification</span></span>

<span data-ttu-id="e43f2-138">詳細については、「[C# 言語の仕様](/dotnet/csharp/language-reference/language-specification/introduction)」の「[例外](~/_csharplang/spec/exceptions.md)」を参照してください。</span><span class="sxs-lookup"><span data-stu-id="e43f2-138">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="e43f2-139">言語仕様は、C# の構文と使用法に関する信頼性のある情報源です。</span><span class="sxs-lookup"><span data-stu-id="e43f2-139">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="e43f2-140">参照</span><span class="sxs-lookup"><span data-stu-id="e43f2-140">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="e43f2-141">C# プログラミングガイド</span><span class="sxs-lookup"><span data-stu-id="e43f2-141">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="e43f2-142">C# のキーワード</span><span class="sxs-lookup"><span data-stu-id="e43f2-142">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="e43f2-143">throw</span><span class="sxs-lookup"><span data-stu-id="e43f2-143">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="e43f2-144">try-catch</span><span class="sxs-lookup"><span data-stu-id="e43f2-144">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="e43f2-145">try-finally</span><span class="sxs-lookup"><span data-stu-id="e43f2-145">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="e43f2-146">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="e43f2-146">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="e43f2-147">例外</span><span class="sxs-lookup"><span data-stu-id="e43f2-147">Exceptions</span></span>](../../../standard/exceptions/index.md)
